export const mockProducts = [
  // Site 1: Petal & Bloom - Artisan Flower Shop
  {
    id: "1",
    siteId: "1",
    name: "Classic Rose Bouquet",
    sku: "ROS-001",
    price: 65.99,
    stock: 12,
    status: "published",
    category: "Bouquets",
    description: "A stunning arrangement of 12 fresh premium roses, elegantly wrapped with silk ribbon. Perfect for expressing love and appreciation.",
    imageUrl: "https://images.unsplash.com/photo-1672243691196-9b7f64cce1c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaW5rJTIwcm9zZXMlMjBib3VxdWV0fGVufDF8fHx8MTc2MjI0NTQxOXww&ixlib=rb-4.1.0&q=80&w=1080",
    tags: ["roses", "romance", "premium"],
  },
  {
    id: "2",
    siteId: "1",
    name: "Spring Tulip Collection",
    sku: "TUL-002",
    price: 45.99,
    stock: 8,
    status: "published",
    category: "Bouquets",
    description: "Vibrant tulips in a rainbow of colors, hand-picked and arranged to bring the beauty of spring into any space.",
    imageUrl: "https://images.unsplash.com/photo-1649853619910-0fe696c80705?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dWxpcHMlMjBmbG93ZXJzfGVufDF8fHx8MTc2MjIwNzI3MXww&ixlib=rb-4.1.0&q=80&w=1080",
    tags: ["tulips", "spring", "colorful"],
  },
  {
    id: "3",
    siteId: "1",
    name: "Sunflower Sunshine",
    sku: "SUN-003",
    price: 52.99,
    stock: 15,
    status: "published",
    category: "Bouquets",
    description: "Bright and cheerful sunflowers that radiate warmth and happiness. These golden blooms are perfect for brightening anyone's day.",
    imageUrl: "https://images.unsplash.com/photo-1593003520741-64323f3aea7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdW5mbG93ZXJzJTIwYXJyYW5nZW1lbnR8ZW58MXx8fHwxNzYyMjcyNTA5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    tags: ["sunflowers", "cheerful", "summer"],
  },
  {
    id: "4",
    siteId: "1",
    name: "Elegant Orchid Plant",
    sku: "ORC-004",
    price: 89.99,
    stock: 6,
    status: "published",
    category: "Plants",
    description: "A sophisticated potted orchid with cascading blooms. This long-lasting plant adds elegance to any home or office.",
    imageUrl: "https://images.unsplash.com/photo-1613474877430-d06a1e2f6361?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvcmNoaWQlMjBwbGFudHN8ZW58MXx8fHwxNzYyMjQ5NjI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    tags: ["orchid", "plant", "elegant"],
  },
  {
    id: "5",
    siteId: "1",
    name: "Lavender Dreams Bundle",
    sku: "LAV-005",
    price: 38.99,
    stock: 20,
    status: "published",
    category: "Specialty",
    description: "Fragrant dried lavender bundles, perfect for home décor or aromatherapy. Each bundle is carefully dried to preserve its natural beauty and scent.",
    imageUrl: "https://images.unsplash.com/photo-1744451619999-1bd41df44f0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXZlbmRlciUyMGJvdXF1ZXR8ZW58MXx8fHwxNzYyMjcyNTEwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    tags: ["lavender", "dried", "aromatherapy"],
  },
  {
    id: "6",
    siteId: "1",
    name: "Garden Mix Bouquet",
    sku: "MIX-006",
    price: 58.99,
    stock: 18,
    status: "published",
    category: "Bouquets",
    description: "A delightful mix of seasonal flowers in complementary colors, artfully arranged by our expert florists for a garden-fresh look.",
    imageUrl: "https://images.unsplash.com/photo-1642728265490-2ea6c3320880?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaXhlZCUyMGZsb3dlciUyMGJvdXF1ZXR8ZW58MXx8fHwxNzYyMjE3NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    tags: ["mixed", "seasonal", "colorful"],
  },
  // Site 2: Eco Living Shop - Eco-Friendly & Lifestyle
  {
    id: "6",
    siteId: "2",
    name: "Bamboo Cutlery Set",
    sku: "BCS-006",
    price: 24.99,
    stock: 150,
    status: "published",
    category: "Eco-Friendly",
    description: "Reusable bamboo cutlery set with carrying case, perfect for on-the-go meals.",
    imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=500&q=80",
    tags: ["bamboo", "eco-friendly", "reusable"],
  },
  {
    id: "7",
    siteId: "2",
    name: "Stainless Steel Water Bottle",
    sku: "SWB-007",
    price: 34.99,
    stock: 85,
    status: "published",
    category: "Eco-Friendly",
    description: "Insulated stainless steel bottle keeps drinks cold for 24 hours, hot for 12 hours.",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&q=80",
    tags: ["water bottle", "insulated", "eco-friendly"],
  },
  {
    id: "8",
    siteId: "2",
    name: "Beeswax Food Wraps",
    sku: "BFW-008",
    price: 18.99,
    stock: 200,
    status: "published",
    category: "Eco-Friendly",
    description: "Set of 5 reusable beeswax wraps to replace plastic wrap in your kitchen.",
    imageUrl: "https://images.unsplash.com/photo-1581579186913-45ac3e648632?w=500&q=80",
    tags: ["beeswax", "kitchen", "zero-waste"],
  },
  {
    id: "9",
    siteId: "2",
    name: "Organic Cotton Tote Bag",
    sku: "OCT-009",
    price: 16.99,
    stock: 0,
    status: "published",
    category: "Eco-Friendly",
    description: "Sturdy organic cotton tote bag with reinforced handles, perfect for shopping.",
    imageUrl: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&q=80",
    tags: ["tote", "organic", "reusable"],
  },
  {
    id: "10",
    siteId: "2",
    name: "Bamboo Toothbrush Set",
    sku: "BTS-010",
    price: 12.99,
    stock: 175,
    status: "published",
    category: "Eco-Friendly",
    description: "Pack of 4 biodegradable bamboo toothbrushes with soft bristles.",
    imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=500&q=80",
    tags: ["bamboo", "toothbrush", "biodegradable"],
  },
  // Site 3: Fashion Forward - Apparel & Fashion
  {
    id: "11",
    siteId: "3",
    name: "Classic Denim Jacket",
    sku: "CDJ-011",
    price: 89.99,
    stock: 45,
    status: "published",
    category: "Apparel",
    description: "Timeless denim jacket with vintage wash and adjustable waist tabs.",
    imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80",
    tags: ["denim", "jacket", "casual"],
  },
  {
    id: "12",
    siteId: "3",
    name: "Organic Cotton T-Shirt",
    sku: "OCT-012",
    price: 29.99,
    stock: 200,
    status: "published",
    category: "Apparel",
    description: "Soft, breathable organic cotton t-shirt in classic fit. Available in multiple colors.",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80",
    tags: ["clothing", "organic", "cotton"],
  },
  {
    id: "13",
    siteId: "3",
    name: "Slim Fit Chinos",
    sku: "SFC-013",
    price: 69.99,
    stock: 80,
    status: "published",
    category: "Apparel",
    description: "Modern slim-fit chinos in stretch cotton blend for all-day comfort.",
    imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&q=80",
    tags: ["pants", "chinos", "casual"],
  },
  {
    id: "14",
    siteId: "3",
    name: "Knit Sweater",
    sku: "KSW-014",
    price: 79.99,
    stock: 60,
    status: "published",
    category: "Apparel",
    description: "Cozy cable-knit sweater in premium merino wool blend.",
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80",
    tags: ["sweater", "knitwear", "winter"],
  },
  {
    id: "15",
    siteId: "3",
    name: "Canvas Sneakers",
    sku: "CSN-015",
    price: 54.99,
    stock: 95,
    status: "published",
    category: "Apparel",
    description: "Classic low-top canvas sneakers with cushioned insole and rubber sole.",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500&q=80",
    tags: ["shoes", "sneakers", "casual"],
  },
  // Preview-only products for site drafts
  {
    id: "preview-1",
    siteId: "preview",
    name: "Signature Preview Candle",
    sku: "PRE-001",
    price: 29.99,
    stock: 25,
    status: "published",
    category: "Showcase",
    description: "A warm amber and cedarwood blend used on preview storefronts to demonstrate merchandising.",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    tags: ["preview", "signature", "candle"],
  },
  {
    id: "preview-2",
    siteId: "preview",
    name: "Limited Edition Tote",
    sku: "PRE-002",
    price: 34.99,
    stock: 40,
    status: "published",
    category: "Showcase",
    description: "Organic cotton tote featuring the store name, ideal for showcasing branding in demo sites.",
    imageUrl: "https://images.unsplash.com/photo-1542293787938-4d2226c12e77?auto=format&fit=crop&w=800&q=80",
    tags: ["preview", "tote", "merch"],
  },
  {
    id: "preview-3",
    siteId: "preview",
    name: "Ceramic Espresso Set",
    sku: "PRE-003",
    price: 49.99,
    stock: 18,
    status: "published",
    category: "Showcase",
    description: "Hand-glazed espresso cups that highlight curated lifestyle imagery for preview experiences.",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    tags: ["preview", "ceramic", "espresso"],
  },
];

export const mockOrders = [
  {
    id: "ORD-1001",
    siteId: "1",
    customerName: "Sarah Johnson",
    customerEmail: "sarah.j@email.com",
    date: "2025-11-02",
    total: 389.98,
    status: "delivered",
    items: [
      { productId: "1", quantity: 1, price: 299.99 },
      { productId: "3", quantity: 1, price: 89.99 },
    ],
  },
  {
    id: "ORD-1002",
    siteId: "1",
    customerName: "Michael Chen",
    customerEmail: "m.chen@email.com",
    date: "2025-11-01",
    total: 479.98,
    status: "processing",
    items: [
      { productId: "2", quantity: 1, price: 399.99 },
      { productId: "5", quantity: 1, price: 79.99 },
    ],
  },
  {
    id: "ORD-1003",
    siteId: "2",
    customerName: "Emma Davis",
    customerEmail: "emma.d@email.com",
    date: "2025-10-31",
    total: 71.97,
    status: "shipped",
    items: [
      { productId: "7", quantity: 1, price: 34.99 },
      { productId: "8", quantity: 1, price: 18.99 },
      { productId: "9", quantity: 1, price: 16.99 },
    ],
  },
  {
    id: "ORD-1004",
    siteId: "3",
    customerName: "James Wilson",
    customerEmail: "j.wilson@email.com",
    date: "2025-11-03",
    total: 244.97,
    status: "delivered",
    items: [
      { productId: "11", quantity: 1, price: 89.99 },
      { productId: "12", quantity: 2, price: 29.99 },
      { productId: "15", quantity: 2, price: 54.99 },
    ],
  },
];

export const mockUsers = [
  // Site 1: TechGadgets Store
  {
    id: "1",
    siteId: "1",
    name: "Alice Cooper",
    email: "alice@example.com",
    role: "Community Manager",
    status: "active",
    lastActive: "2025-11-03",
  },
  {
    id: "2",
    siteId: "1",
    name: "Bob Martin",
    email: "bob@example.com",
    role: "Stock Manager",
    status: "active",
    lastActive: "2025-11-02",
  },
  // Site 2: Eco Living Shop
  {
    id: "3",
    siteId: "2",
    name: "Carol White",
    email: "carol@example.com",
    role: "Community Manager",
    status: "inactive",
    lastActive: "2025-10-28",
  },
  {
    id: "4",
    siteId: "2",
    name: "David Brown",
    email: "david@example.com",
    role: "Stock Manager",
    status: "active",
    lastActive: "2025-11-03",
  },
  // Site 3: Fashion Forward
  {
    id: "5",
    siteId: "3",
    name: "Eva Green",
    email: "eva@example.com",
    role: "Community Manager",
    status: "active",
    lastActive: "2025-11-02",
  },
];

export const mockAuditLog = [
  {
    id: "1",
    siteId: "1",
    user: "Alice Cooper",
    action: "Updated product",
    details: "Changed price for Wireless Headphones Pro",
    timestamp: "2025-11-03 14:23:00",
  },
  {
    id: "2",
    siteId: "1",
    user: "Bob Martin",
    action: "Restocked product",
    details: "Added 50 units to Smart Watch Series 5",
    timestamp: "2025-11-03 11:15:00",
  },
  {
    id: "3",
    siteId: "1",
    user: "Alice Cooper",
    action: "Published product",
    details: "Published Wireless Gaming Mouse",
    timestamp: "2025-11-02 09:30:00",
  },
  {
    id: "4",
    siteId: "2",
    user: "Admin",
    action: "Created user",
    details: "Invited Carol White as Community Manager",
    timestamp: "2025-11-02 16:45:00",
  },
  {
    id: "5",
    siteId: "2",
    user: "David Brown",
    action: "Restocked product",
    details: "Added 75 units to Bamboo Toothbrush Set",
    timestamp: "2025-11-02 10:30:00",
  },
  {
    id: "6",
    siteId: "2",
    user: "David Brown",
    action: "Updated product",
    details: "Marked Organic Cotton Tote Bag as out of stock",
    timestamp: "2025-11-01 15:20:00",
  },
  {
    id: "7",
    siteId: "3",
    user: "Eva Green",
    action: "Created product",
    details: "Added new product: Canvas Sneakers",
    timestamp: "2025-11-03 10:15:00",
  },
  {
    id: "8",
    siteId: "3",
    user: "Eva Green",
    action: "Updated product",
    details: "Changed description for Classic Denim Jacket",
    timestamp: "2025-11-01 14:45:00",
  },
];

export const mockSites = [
  {
    id: "1",
    name: "Petal & Bloom Florals",
    url: "petalandbloom.shopifake.com",
    status: "active",
    products: 6,
    orders: 234,
    revenue: 15680.00,
  },
  {
    id: "2",
    name: "Eco Living Shop",
    url: "ecoliving.shopifake.com",
    status: "active",
    products: 5,
    orders: 89,
    revenue: 5680.00,
  },
  {
    id: "3",
    name: "Fashion Forward",
    url: "fashionforward.shopifake.com",
    status: "inactive",
    products: 5,
    orders: 234,
    revenue: 18900.00,
  },
];

export const mockRevenueData = [
  { month: "May", revenue: 4200 },
  { month: "Jun", revenue: 5100 },
  { month: "Jul", revenue: 4800 },
  { month: "Aug", revenue: 6300 },
  { month: "Sep", revenue: 7200 },
  { month: "Oct", revenue: 8500 },
  { month: "Nov", revenue: 9800 },
];

export const mockCategoryData = [
  { name: "Electronics", value: 33 },
  { name: "Eco-Friendly", value: 33 },
  { name: "Apparel", value: 34 },
];
